---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empire-hq
spec:
  selector:
    matchLabels:
      app: empire-hq
  replicas: 1
  template:
    metadata:
      labels:
        app: empire-hq
    spec:
      containers:
      - name: empire-hq
        image: postgres
        command: ["sleep"]
        args: ["30000"]
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empire-outpost
spec:
  selector:
    matchLabels:
      app: empire-outpost
  replicas: 1
  template:
    metadata:
      labels:
        app: empire-outpost
    spec:
      containers:
      - name: empire-outpost
        image: postgres
        command: ["sleep"]
        args: ["30000"]
