apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-server
spec:
  selector:
   matchLabels:
    app: post-server
  replicas: 1
  template:
    metadata:
      labels:
        app: post-server
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
         
          
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
