kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: px-postgres-pvc
    annotations:
      volume.beta.kubernetes.io/storage-class: px-repl3-sc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 1Gi
  
